### PR TITLE
Minor updates to Plot.py

### PR DESCRIPTION
**Pull request by fyodr**
Two small commits. Should still comply with doctests/standards, but maybe look at usage changes in _get_ReticlesPerImage.

### CODE REVIEW

**Comment by demisjohn** [comment]
Thanks, will review in a Few days.

**Comment by demisjohn** [comment]
@fyodr can you run your updated codebase and compile `Example 1` and `Example 2` for me please?  Send me the resulting TXT file and I'll do a `diff` to compare to the knwon-good versions.  Then we can complete the PULL.  (This is like a manual unittest).

**Comment by demisjohn** [comment]
@fyodr sorry if i missed an email to this effect - did you ever confirm correct compilation of the 2 example files?  Send to me and I'll convert them on the ASML.

**Comment by fyodr** [comment]
Hi Demis,

I think I did send an email about this a while back, but I did not reply on
github. My bad there.

Best,
Ted

**Pull request merged**
